---
- hosts: local
  connection: local  
  tasks:
    - name: Start a task
      ecs_task:
        operation: start
        cluster: "{{ cluster_name }}"
        task_definition: "{{ task_def }}"
        task: "{{ task_arn }}" 
 
        container_instances: 
        - "{{ container_instance }}"
        started_by: "{{ ansible_user }}"
      register: task_output
  environment:
    AWS_REGION: us-west-2
    EC2_SECURITY_TOKEN:  
  vars:
    cluster_name: testcluster
    task_def: test_task
    
    container_instance: arn:aws:ecs:us-west-2:967879827194:container-instance/1164d637-7831-46d0-a5ed-80a45578536d
    task_arn: arn:aws:ecs:us-west-2:967879827194:task/b70868b0-9871-48cc-9fd4-b7d134bbff38 
    
