---
- hosts: local
  tasks: 
    - name: Start a task
      ecs_task:
        operation: start
        cluster: docker-aws1 
        task_definition: test2-taskdefinition
        task: "arn:aws:ecs:us-west-2:555075547139:task/6feb2968-3ebb-40e9-a927-27430c8a589b"

        container_instances: 
        - arn:aws:ecs:us-west-2:555075547139:container-instance/11607e48-5286-4a3d-b914-42a7913880be
        started_by: ansible_user
      register: task_output
  environment:
    AWS_REGION: us-west-2 
