---
# tasks file for ecs_starttask
- name: Run task
  ecs_task:
    operation: run
    cluster: test-automation
    task_definition: test-auto
    count: 1
    started_by: ansible_user
  register: task_output
