---
- hosts: local
  tasks:
    - name: Stop a task
      ecs_task:
        operation: stop
        cluster: test-automation
        task_definition: test-auto
        task: "arn:aws:ecs:us-west-2:555075547139:task/1240bfcb-b26b-4273-968e-4724c0f9bf0a"
  environment:
    AWS_REGION: us-west-2  
