---
- hosts: local
  tasks:
    - name: Stop a task
      ecs_task:
        operation: stop
        cluster: docker-testserver
        task_definition: test2-taskdefinition
        task: "arn:aws:ecs:us-west-2:555075547139:task/6feb2968-3ebb-40e9-a927-27430c8a589b"
  environment:
    AWS_REGION: us-west-2  
