---
# tasks file for ecs_task
- name: Create task definition
  ecs_taskdefinition:
    containers:
    - name: test-auto
      cpu: 1
      essential: true
      image: "httpd:latest"
      memory: 300
      mountPoints:
      - containerPath: /usr/local/apache2/htdocs
        sourceVolume: my-vol
      portMappings:
      - containerPort: 6022
        hostPort: 80
      - containerPort: 6023
        hostPort: 22
      - containerPort: 8081
        hostPort: 8081
 
    volumes:
    - name: my-vol
    family: test-php
    state: present
  register: task_output
